name: example
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_modular: ^4.0.1+2
  flutter_triple: ^1.2.4+3
  rx_notifier: ^1.1.0
  
dev_dependencies:
  modular_test: ^1.0.1
  flutter_test:
    sdk: flutter
  triple_test: ^0.0.5
flutter:
  uses-material-design: true
scripts:
  mobx: fvm flutter pub get & fvm flutter pub run build_runner watch  --delete-conflicting-outputs
  mobb: flutter pub get & flutter pub run build_runner build  --delete-conflicting-outputs
  mobd: flutter pub get & flutter pub run build_runner build
  mobw: fvm flutter pub get & fvm flutter pub run build_runner watch
  build_apk: flutter pub get & flutter build apk -t lib/main_production.dart --release
  build_apk_qa: fvm flutter pub get & fvm flutter build apk --flavor qa -t  lib/main_qa.dart --release
  build_apk_prod: fvm flutter pub get & fvm flutter build apk --flavor prod -t  lib/main_production.dart --release
  build_ios: flutter pub get &  flutter build ios -t lib/main_production.dart --flavor prod --release
  build_web: flutter pub get & flutter build web -t lib/main_production.dart --release
  localization: dart lib\app\commands\localization.dart
  test: flutter pub get
  test_error: flutter pub get2
  print: echo $name
vars:
  name: jacob