name: slidy
description: CLI package manager and template for Flutter. Generate Modules, Pages, Widgets, BLoCs, MobX, Triple and more.
version: 3.0.0
homepage: https://github.com/Flutterando/slidy

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dart_console: ^1.0.0
  either_dart: ^0.1.0-nullsafety.1
  http: ^0.13.0
  args: ^2.0.0
  ansicolor: ^2.0.0-nullsafety.0
  recase: ^4.0.0-nullsafety.0
  file: ^6.1.0

dev_dependencies:
  test: ^1.16.0-nullsafety.17
  mocktail: 0.0.1-dev.12

# dependency_overrides:
#   args: '2.0.0-nullsafety.0'


executables:
  slidy: slidy
